apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-transcript
  namespace: youtube-transcript
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: text-youtube.com  # Cambia esto por tu dominio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: youtube-transcript-service
            port:
              number: 80
