apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-transcript
  namespace: youtube-transcript
  annotations:
    # Indica a Traefik que use ambos entrypoints
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # Habilita TLS en el router
    traefik.ingress.kubernetes.io/router.tls: "true"
    # (Opcional) Middleware para redirigir HTTP a HTTPS
    # traefik.ingress.kubernetes.io/router.middlewares: youtube-transcript/redirect-to-https@kubernetescrd
    # Indica a Cert Manager que use el ClusterIssuer para obtener el certificado
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - text-youtube.com
    secretName: text-youtube-tls  # Este Secret será creado y actualizado por Cert Manager
  rules:
  - host: text-youtube.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: youtube-transcript-service
            port:
              number: 80
