apiVersion: v1
kind: Service
metadata:
  name: youtube-transcript-service
  namespace: youtube-transcript
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: youtube-transcript
